apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: controller
  newName: kind-local:5000/minagflow/agent-flow-planner
  newTag: latest
resources:
- deployment.yaml
- service.yaml
