---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - agentflow.io
  resources:
  - tasks
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentflow.io
  resources:
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - agentflow.io
  resources:
  - tasks/status
  - workflows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
