// Package v1alpha1 contains API Schema definitions for the agentflow.io v1alpha1 API group.
// +kubebuilder:object:generate=true
// +groupName=agentflow.io
package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Editor NOTE: Edit these types to define the custom resources for your Operator.
// You can define Task, Worker, and Monitor custom resources.

// TaskSpec defines the desired state of Task.
// +k8s:deepcopy-gen=true
type TaskSpec struct {
	// Command is the command to execute
	Command []string `json:"command"`

	// Args are the arguments for the command
	Args []string `json:"args,omitempty"`

	// Image is the container image to use
	Image string `json:"image,omitempty"`

	// Env are environment variables
	Env []corev1.EnvVar `json:"env,omitempty"`

	// Resources define resource requirements
	Resources corev1.ResourceRequirements `json:"resources,omitempty"`

	// +k8s:deepcopy-gen=true
	// RetryPolicy defines retry behavior
	RetryPolicy RetryPolicy `json:"retryPolicy,omitempty"`

	// TimeoutSeconds is the maximum execution time
	TimeoutSeconds *int32 `json:"timeoutSeconds,omitempty"`

	// RuntimeClassName is the runtime class to use (e.g., gvisor, kata)
	RuntimeClassName *string `json:"runtimeClassName,omitempty"`

	// PodSecurityContext defines the security context for the sandbox pod
	// Supports gVisor/Kata strong isolation configuration
	// +optional
	PodSecurityContext *corev1.PodSecurityContext `json:"podSecurityContext,omitempty"`
}

// TaskOutput defines the output generated by the Worker.
// +k8s:deepcopy-gen=true
type TaskOutput struct {
	// Content is the text output content (for small outputs < 256KB)
	Content string `json:"content,omitempty"`

	// Format indicates the output type: text, code, json, etc.
	Format string `json:"format,omitempty"`

	// GeneratedAt is when the output was generated
	GeneratedAt *metav1.Time `json:"generatedAt,omitempty"`
}

// TokenUsage records LLM token consumption for a task.
// +k8s:deepcopy-gen=true
type TokenUsage struct {
	PromptTokens     int32 `json:"promptTokens,omitempty"`
	CompletionTokens int32 `json:"completionTokens,omitempty"`
	TotalTokens      int32 `json:"totalTokens,omitempty"`
}

// QualityDimensions holds per-dimension evaluation scores.
// +k8s:deepcopy-gen=true
type QualityDimensions struct {
	Completeness int32 `json:"completeness,omitempty"`
	Accuracy     int32 `json:"accuracy,omitempty"`
	Quality      int32 `json:"quality,omitempty"`
}

// QualityCheck defines the quality evaluation result from Monitor.
// +k8s:deepcopy-gen=true
type QualityCheck struct {
	// Score is the quality score (0-100)
	Score int32 `json:"score,omitempty"`

	// Passed indicates whether the quality check passed
	Passed bool `json:"passed,omitempty"`

	// Feedback is the Monitor's feedback for retry improvement
	Feedback string `json:"feedback,omitempty"`

	// EvaluatedAt is when the quality check was performed
	EvaluatedAt *metav1.Time `json:"evaluatedAt,omitempty"`

	// Dimensions holds per-dimension scores
	Dimensions *QualityDimensions `json:"dimensions,omitempty"`

	// Issues lists concrete problems found during evaluation
	Issues []string `json:"issues,omitempty"`

	// TaskType is the detected evaluation rubric (poetry, code, general)
	TaskType string `json:"taskType,omitempty"`

	// Attempt is the evaluation attempt number (0-based)
	Attempt int32 `json:"attempt,omitempty"`

	// CheckMethod indicates how the score was produced (rule, ai, hybrid)
	CheckMethod string `json:"checkMethod,omitempty"`
}

// TaskStatus defines the observed state of Task.
// +k8s:deepcopy-gen=true
type TaskStatus struct {
	// Phase is the current state of the task
	Phase TaskPhase `json:"phase"`

	// Message provides additional status information
	Message string `json:"message,omitempty"`

	// StartTime is when the task started
	StartTime *metav1.Time `json:"startTime,omitempty"`

	// CompletionTime is when the task completed
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`

	// StartTimeUnix is when the task started (Unix timestamp)
	StartTimeUnix int64 `json:"startTimeUnix,omitempty"`

	// CompletionTimeUnix is when the task completed (Unix timestamp)
	CompletionTimeUnix int64 `json:"completionTimeUnix,omitempty"`

	// Retries is the number of retry attempts
	Retries int32 `json:"retries,omitempty"`

	// Output is the task output generated by Worker
	Output *TaskOutput `json:"output,omitempty"`

	// QualityCheck is the quality evaluation result from Monitor
	QualityCheck *QualityCheck `json:"qualityCheck,omitempty"`

	// TokenUsage is cumulative LLM token consumption for this task.
	TokenUsage *TokenUsage `json:"tokenUsage,omitempty"`

	// WorkerName is the name of the worker that executed this task
	WorkerName string `json:"workerName,omitempty"`
}

// TaskPhase represents the phase of a task
type TaskPhase string

const (
	TaskPhasePending   TaskPhase = "Pending"
	TaskPhaseRunning   TaskPhase = "Running"
	TaskPhaseSucceeded TaskPhase = "Succeeded"
	TaskPhaseFailed    TaskPhase = "Failed"
	TaskPhaseCancelled TaskPhase = "Cancelled"
)

// RetryPolicy defines retry behavior.
// +k8s:deepcopy-gen=true
type RetryPolicy struct {
	// MaxRetries is the maximum number of retry attempts
	MaxRetries int32 `json:"maxRetries"`

	// RetryDelaySeconds is the delay between retries
	RetryDelaySeconds int32 `json:"retryDelaySeconds,omitempty"`

	// RetryOn indicates which conditions should trigger a retry
	RetryOn []TaskCondition `json:"retryOn,omitempty"`
}

// TaskCondition indicates when a retry should be triggered
type TaskCondition string

const (
	TaskConditionOnFailure  TaskCondition = "OnFailure"
	TaskConditionOnTimeout  TaskCondition = "OnTimeout"
	TaskConditionOnAnyError TaskCondition = "OnAnyError"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.phase",description="Current status of the task"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",description="Time since creation"
// +kubebuilder:storageversion

// Task is the Schema for the tasks API
type Task struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TaskSpec   `json:"spec,omitempty"`
	Status TaskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TaskList contains a list of Task
type TaskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Task `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Task{}, &TaskList{})
}
